export const Routes = {
  HOME: '/',
  TOURIST_LOGIN: '/tourist/login',
  TOURIST_SIGN_UP: '/tourist/signup',
  TOURIST_PROFILE: '/tourist/profile',
  AGENCY_LOGIN: '/agency/login',
  AGENCY_SIGN_UP: '/agency/sign-up',
  SIGNUP_EMPLOYEE: '/agency/signup-employee/:token',
  AGENCY_PROFILE: '/agency/profile',
  DESTINATIONS: '/destinations',
  DESTINATIONPAGE: '/destination/:slug',
  CONTACT: '/contact',
  ABOUT: '/about',
  BLOGS: '/blogs',
  BLOGPAGE: '/blog/:id',
};
