import type { Metadata } from 'next';
import { Jost, Fredoka } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import TanstackProvider from '@/components/providers/tanstack.provider';
import { Toaster } from '@/components/ui/toaster';

const jost = Jost({
  weight: ['400', '700'],
  subsets: ['latin-ext'],
  variable: '--font-jost',
});

const fredoka = Fredoka({
  subsets: ['latin-ext'],
  variable: '--font-fredoka',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${fredoka.variable}`}>
        <TanstackProvider>
          <Navbar />
          <main className="relative flex flex-col min-h-screen">
            {children}
          </main>
          <Toaster />
        </TanstackProvider>
      </body>
    </html>
  );
}
